repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.1
    hooks:
    -   id: ruff-check
        files: ^oioioi/
        args: [ --fix, --exit-non-zero-on-fix ]
    -   id: ruff-format